easy_admin:
    list:
        actions: ['execute']
    entities:
        # List the entity class name you want to manage
        SSHCommand:
            class: App\Entity\Actions\SSHCommand
        Automation:
            class: App\Entity\Automation
        Device:
            class: App\Entity\Device
            list:
                actions: ['-execute']
